### ISSUE TITLE
Get payments attached to event

### ISSUE THREAD

**Issue by rhaeyx** [SAMAHAN-Systems-Development/ACMS-backend-2023#28]
**Trigger**
Clicking View Pending Payments in View Event page
Clicking View Accepted Payments in View Event page
Clicking View Declined Payments in View Event page

**Page**
![Sample](https://github.com/SAMAHAN-Systems-Development/ACMS-backend-2023/assets/43877303/209eb90d-f856-4cb5-a0d8-8b9f3711e279)

**Requirements**

- [ ] Endpoints should be
    - [ ] /payment/pending/{eventId}
    - [ ] /payment/accepted/{eventId}
    - [ ] /payment/declined/{eventId}
- [ ] Will return a list of events
- [ ] Pagination

**Comment by p0tatoes** [comment]
> Will return a list of events

should this be return "a list of payments?"

**Comment by p0tatoes** [comment]
> will return a list of events

should this be "return a list of payments?"
